name: "MNIST_testModel"
backend: "onnxruntime"
max_batch_size: 100
input [
    {
        name: "flatten_input:0"
        data_type: TYPE_FP32
        dims: [28, 28]
    }
]

output [
    {
        name: "dense_1/Softmax:0"
        data_type: TYPE_FP32
        dims: [10]
    }
]
